nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "http://34.42.217.201:4873/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
